/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import com.mysql.jdbc.PreparedStatement;
import conexionSQL.ConexionSQL;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SENA
 */
public class Sistema extends javax.swing.JFrame {

    ConexionSQL cc = new ConexionSQL();
    Connection con = cc.conexion();

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        initComponents();
        this.setLocationRelativeTo(null); //centro de la pantalla
        this.getContentPane().setBackground(getBackground());// fondo de panel
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipo_documento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        num_documento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Nuevo = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAprendiz = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATOS DEL USUARIO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Digite su infromacion");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de Documento:");

        tipo_documento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Pasaporte", "Cédula de Ciudadanía", " " }));
        tipo_documento.setToolTipText("Elija su tipo de documento.");
        tipo_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_documentoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Numero de documento:");

        num_documento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        num_documento.setToolTipText("Escriba su numero de documento");
        num_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_documentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombres:");

        nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombres.setToolTipText("Escriba su nombre completo");
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Genero:");

        genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino", "Femenino", " " }));
        genero.setToolTipText("elija su orientaciòn sexual");
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Direccion:");

        direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        direccion.setToolTipText("Escriba su direccion de donde vive, el numeral se cambia y escribes Nº.");
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Celular:");

        celular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        celular.setToolTipText("Escriba su numero de celular personal.");
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("buscar:");

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscar.setToolTipText("buscador de la informaciòn que necesites.");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        Nuevo.setBackground(new java.awt.Color(51, 204, 255));
        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.setToolTipText("Se limpiara el formulario.");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(51, 204, 255));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setToolTipText("Se guardo los cambios.");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(51, 204, 255));
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setToolTipText("Se a actualizado su datos.");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(51, 204, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setToolTipText("Se eliminara de la base de datos.");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Nuevo)
                .addGap(33, 33, 33)
                .addComponent(Guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Actualizar)
                .addGap(48, 48, 48)
                .addComponent(Eliminar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo)
                    .addComponent(Guardar)
                    .addComponent(Actualizar)
                    .addComponent(Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaAprendiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAprendiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAprendizMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAprendiz);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(106, 106, 106))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipo_documento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num_documento)
                                    .addComponent(nombres, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(direccion)
                                    .addComponent(celular)))
                            .addComponent(jScrollPane1))
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tipo_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_documentoActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        filtrarDatos(buscar.getText());


    }//GEN-LAST:event_buscarActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void tablaAprendizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAprendizMouseClicked
        int filaSeleccionada = tablaAprendiz.rowAtPoint(evt.getPoint());
        tipo_documento.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada, 0));
        num_documento.setText(tablaAprendiz.getValueAt(filaSeleccionada, 1).toString());
        nombres.setText(tablaAprendiz.getValueAt(filaSeleccionada, 2).toString());
        genero.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada, 3));
        direccion.setText(tablaAprendiz.getValueAt(filaSeleccionada, 4).toString());
        celular.setText(tablaAprendiz.getValueAt(filaSeleccionada, 5).toString());
    }//GEN-LAST:event_tablaAprendizMouseClicked

    private void num_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_documentoActionPerformed

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        limpiarDatos();

    }//GEN-LAST:event_NuevoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        insertarDatos();
        limpiarDatos();
        mostrarDatos();

    }//GEN-LAST:event_GuardarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed

        actualizarDatos();
        limpiarDatos();
        mostrarDatos();

    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        eliminarDatos();
        limpiarDatos();
        mostrarDatos();

    }//GEN-LAST:event_EliminarActionPerformed

    public void insertarDatos() {
        try {
            //Datos que van a insertar en la base de datos
            String SQL = "insert into aprendiz (tipo_documento,num_documento,Nombres,Genero,Gireccion,Celular)values(?,?,?,?,?,?)";//insetar los datos

            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            int seleccionado = tipo_documento.getSelectedIndex();
            pst.setString(1, tipo_documento.getItemAt(seleccionado));

            pst.setInt(2, Integer.parseInt(num_documento.getText()));
            pst.setString(3, nombres.getText());

            int seleccionado1 = genero.getSelectedIndex();
            pst.setString(4, genero.getItemAt(seleccionado1));

            pst.setString(5, direccion.getText());

            pst.setDouble(6, Double.parseDouble(celular.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(null, "Datos Registrados Correctamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Registro." + e.getMessage());
        }
    }

    public void limpiarDatos() {
        tipo_documento.setSelectedItem(null);
        num_documento.setText(null);
        nombres.setText(null);
        genero.setSelectedItem(null);
        direccion.setText(null);
        celular.setText(null);
    }

    public void mostrarDatos() {
        String[] titulos = {"Tipo", "Documento", "Nombres", "Genero", "Direccion", "Celular"};
        String[] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //String sentencia ="SELECT *"+"FROM aprendiz";
        String SQL = "select * from aprendiz1";

        try {
            Statement st = con.createStatement();
            var rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("tipo_documento");
                registros[1] = rs.getString("num_documento");
                registros[2] = rs.getString("Nombres");
                registros[3] = rs.getString("Genero");
                registros[4] = rs.getString("Direccion");
                registros[5] = rs.getString("Celular");
                modelo.addRow(registros);
            }
            tablaAprendiz.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr de Busqueda" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    public void actualizarDatos() {
        try {

            String SQL = "update aprendiz set tipo_documento=?, num_documento=?, Nombres=?, Genero=?, Direccion=?, Celular=? where documento=?";
            int filaSeleccionada = tablaAprendiz.getSelectedRow();//ahora se convierte a texto lo que se selecciono
            String ref = (String) tablaAprendiz.getValueAt(filaSeleccionada, 1); //variable para la fila seleciconada

            PreparedStatement pst = (PreparedStatement) con.prepareStatement(SQL);
            int seleccionado = tipo_documento.getSelectedIndex();
            pst.setString(1, tipo_documento.getItemAt(seleccionado));

            pst.setDouble(2, Double.parseDouble(num_documento.getText()));
            pst.setString(3, nombres.getText());

            int seleccionadol = genero.getSelectedIndex();
            pst.setString(4, genero.getItemAt(seleccionadol));

            pst.setString(5, direccion.getText());
            pst.setDouble(6, Double.parseDouble(celular.getText()));

            pst.setString(7, ref);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Datos Actualizados Correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Actualizacion" + e.getMessage());
        }
    }

    public void eliminarDatos() {
        int filaSeleccionada = tablaAprendiz.getSelectedRow();

        try {
            String SQL = "delete from aprendiz where documento=" + tablaAprendiz.getValueAt(filaSeleccionada, 1);

            Statement st = con.createStatement();
            int n = st.executeUpdate(SQL);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Al Eliminar Registro" + e.getMessage());
        }
    }

    public void filtrarDatos(String valor) {
        String[] titulos = {"Tipo", "Documento", "Nombres", "Genero", "Direccion", "Celular"};
        String[] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        //String sentencia ="SELECT *"+"FROM aprendiz";
        String SQL = "select * from aprendiz where nombre like '%" + valor + "%' or documento like '%" + valor + "%'";

        try {
            Statement st = con.createStatement();
            var rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("tipo_documento");
                registros[1] = rs.getString("num_documento");
                registros[2] = rs.getString("Nombres");
                registros[3] = rs.getString("Genero");
                registros[4] = rs.getString("Direccion");
                registros[5] = rs.getString("Celular");
                modelo.addRow(registros);
            }
            tablaAprendiz.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr de Registro" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField direccion;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField num_documento;
    private javax.swing.JTable tablaAprendiz;
    private javax.swing.JComboBox<String> tipo_documento;
    // End of variables declaration//GEN-END:variables
}
